### ISSUE TITLE
emoji.js Switch instead of if if if

### ISSUE THREAD

**Issue by KoenHaagsma** [lisannevvliet/ethical-food-checker#10]
You can maybe clean your code here by adding a switch instead of all the if's

**Comment by lisannevvliet** [comment]
Ik zou niet weten hoe, omdat het een object is waarin wordt gezocht. Daarnaast zoek ik niet binnen het gehele object, maar kijk ik per specifiek item wat erin staat. Ik heb dit wel geïmplementeerd voor de Eco-Score.

**Comment by KoenHaagsma** [comment]
Ik kan je hier wel even mee helpen van de week mocht je dat willen

**Comment by lisannevvliet** [comment]
Graag!

**Comment by lisannevvliet** [comment]
In overleg met Koen dit niet geïmplementeerd.
