### ISSUE TITLE
CSS Feedback

### ISSUE THREAD

**Issue by ppijn** [lisannevvliet/ethical-food-checker#11]
https://github.com/lisannevvliet/ethical-food-checker/blob/1e5ca34666b9908a67d7075a7fcbc47c2c4f8fd6/styles/style.css#L1

CSS ziet er goed uit! ik zou alleen misschien comments plaatsten met een korte beschrijving can de sections 

// Search bar //
...

// Product section //
...

**Comment by lisannevvliet** [comment]
Niet geïmplementeerd, maar de CSS staat inmiddels wel op volgorde van de HTML. Het is nu makkelijk om de bijbehorende CSS te vinden.
