### ISSUE TITLE
Js Clean maken

### ISSUE THREAD

**Issue by ppijn** [lisannevvliet/ethical-food-checker#12]
https://github.com/lisannevvliet/ethical-food-checker/blob/1e5ca34666b9908a67d7075a7fcbc47c2c4f8fd6/scripts/modules/render.js#L12-L14

Misschine het enige is dat je als je de html gaat inputten dat je het ook schrijft als html:

ipv: <div><img .... /></div>

zo:

<div>
  <img ... />
</div>

**Comment by lisannevvliet** [comment]
Is het de bedoeling dat er een voorbeeld staat onder "zo:"? Wat bedoel je precies?

**Comment by lisannevvliet** [comment]
Geïmplementeerd.
