### ISSUE TITLE
Consistent code

### ISSUE THREAD

**Issue by jody29** [lisannevvliet/ethical-food-checker#14]
https://github.com/lisannevvliet/ethical-food-checker/blob/16e73a7fcd8887be643521431c3d1534d3cabc55/scripts/modules/emojis.js#L6-L13

Je zou hier eventueel ook een switch statement kunnen gebruiken, net zoals bij de andere module. Dit is wat meer consistent.

**Comment by lisannevvliet** [comment]
Dubbele issue, zie https://github.com/lisannevvliet/ethical-food-checker/issues/10.
