### ISSUE TITLE
inline styles

### ISSUE THREAD

**Issue by KaivWezel** [lisannevvliet/ethical-food-checker#2]
In de get-functie pas je de styles van elementen aan, dit kan je dus mooi doen met classes, dat maakt de code leesbaarder en compactier.

**Comment by KaivWezel** [comment]
Je kan ook deze styling + gevolgen in aparte functies zetten. Dan blijft je fetch een soort "Story" zoals Joost tijdens de les zei.

**Comment by lisannevvliet** [comment]
ID's naar classes omgezet in de meest recente commit.
