### ISSUE TITLE
Elementen in variabelen

### ISSUE THREAD

**Issue by KaivWezel** [lisannevvliet/ethical-food-checker#3]
Ipv je querySelector in een functie te zetten, zet je elementen in variabelen.

VB:
`const loader = document.querySelector("#loader")`

Nu kijk ik toch steeds terug naar wat die functie doet.

**Comment by lisannevvliet** [comment]
Als ik dit zou implementeren zouden er veel meer regels code bijkomen. Kai denkt dat dit qua performance en leesbaarheid wellicht beter zou zijn. Na de vakantie even bespreken met een docent.

**Comment by lisannevvliet** [comment]
Na overweging niet besloten om dit te implementeren.
